### ISSUE TITLE
Typography styles page lists incorrect values for small/extra small

### ISSUE THREAD

**Issue by peterblazejewicz** [OutSystems/outsystems-ui-kit#1]
João
Thanks for excellent resource!
Minor issue:
`small` and `extra small` are listed as `16px / 1.5`, while in fact it should read `14px / 1.5` and `12px / 1.5` IMO.

Not sure if I could make a PR:
https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization

Thanks!

**Comment by joaoguerra-os** [comment]
Hi Peter, thanks for bringing this up.

We are going to address this issue soon and will update it accordingly. For now we prefer to deal with this ourselves to better keep track of the document changes.

Thanks for the help! 😃👍

**Comment by joaoguerra-os** [comment]
Hi Peter,

The issue you reported was fixed in the latest version 1.0.1.

Thanks again for your help and feedback.
